import { BloodGroup, Urgency, BloodRequest } from "./types";

export const BLOOD_GROUPS: BloodGroup[] = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
];
export const URGENCIES: Urgency[] = ["Emergency", "Urgent", "Normal"];

export const ITEMS_PER_PAGE = 5;

export const urgencyConfig: Record<
  string,
  {
    badge: string;
    text: string;
    dot?: string;
    blood: string;
    bloodText: string;
  }
> = {
  emergency: {
    badge: "bg-rose-50 text-rose-600 border border-rose-100",
    text: "text-rose-600",
    dot: "bg-rose-500 animate-ping",
    blood: "bg-rose-50",
    bloodText: "text-rose-600",
  },
  urgent: {
    badge: "bg-amber-50 text-amber-600 border border-amber-100",
    text: "text-amber-600",
    blood: "bg-amber-50",
    bloodText: "text-amber-600",
  },
  normal: {
    badge: "bg-emerald-50 text-emerald-600 border border-emerald-100",
    text: "text-emerald-600",
    blood: "bg-emerald-50",
    bloodText: "text-emerald-600",
  },
};

export const REQUESTS: BloodRequest[] = [
  {
    _id: "1",
    requestNumber: "REQ-2024-001",
    requesterId: {
      _id: "user1",
      fullName: "John Doe",
      email: "john@example.com",
      phone: "01712345678",
      bloodGroup: "O+",
    },
    patientName: "Jane Smith",
    patientAge: 35,
    patientGender: "female",
    patientCondition: "Surgery preparation",
    bloodGroup: "O+",
    unitsRequired: 2,
    componentType: "whole_blood",
    hospital: "Dhaka Medical College Hospital",
    division: "Dhaka",
    district: "Dhaka",
    ward: "Surgery Ward",
    doctorName: "Dr. Ahmed Rahman",
    doctorContact: "01787654321",
    urgencyLevel: "urgent",
    requiredBy: "2024-04-15T10:00:00.000Z",
    requiredByTime: "10:00",
    specialInstructions: "Patient needs O+ blood urgently for surgery",
    requesterName: "John Doe",
    relation: "Husband",
    contactPhone: "01712345678",
    alternatePhone: "01812345678",
    contactEmail: "john@example.com",
    status: "pending",
    notes: "Emergency surgery scheduled",
    createdAt: "2024-04-10T08:30:00.000Z",
    updatedAt: "2024-04-10T08:30:00.000Z",
  },
  {
    _id: "2",
    requestNumber: "REQ-2024-002",
    requesterId: {
      _id: "user2",
      fullName: "Fatima Begum",
      email: "fatima@example.com",
      phone: "01823456789",
      bloodGroup: "A+",
    },
    patientName: "Ahmed Begum",
    patientAge: 45,
    patientGender: "male",
    patientCondition: "Accident victim",
    bloodGroup: "A+",
    unitsRequired: 3,
    componentType: "whole_blood",
    hospital: "Chittagong Medical College Hospital",
    division: "Chittagong",
    district: "Chittagong",
    doctorName: "Dr. Karim Islam",
    doctorContact: "01987654321",
    urgencyLevel: "emergency",
    requiredBy: "2024-04-12T15:00:00.000Z",
    requiredByTime: "15:00",
    specialInstructions: "Critical condition, needs immediate transfusion",
    requesterName: "Fatima Begum",
    relation: "Wife",
    contactPhone: "01823456789",
    contactEmail: "fatima@example.com",
    status: "pending",
    createdAt: "2024-04-11T14:20:00.000Z",
    updatedAt: "2024-04-11T14:20:00.000Z",
  },
  {
    _id: "3",
    requestNumber: "REQ-2024-003",
    requesterId: {
      _id: "user3",
      fullName: "Rahim Khan",
      email: "rahim@example.com",
      phone: "01934567890",
      bloodGroup: "B+",
    },
    patientName: "Sara Khan",
    patientAge: 28,
    patientGender: "female",
    patientCondition: "Childbirth complications",
    bloodGroup: "B+",
    unitsRequired: 2,
    componentType: "platelets",
    hospital: "Rajshahi Medical College Hospital",
    division: "Rajshahi",
    district: "Rajshahi",
    doctorName: "Dr. Nadia Islam",
    doctorContact: "01765432109",
    urgencyLevel: "urgent",
    requiredBy: "2024-04-14T08:00:00.000Z",
    requiredByTime: "08:00",
    specialInstructions: "Post-delivery platelet transfusion needed",
    requesterName: "Rahim Khan",
    relation: "Husband",
    contactPhone: "01934567890",
    alternatePhone: "01634567890",
    contactEmail: "rahim@example.com",
    status: "pending",
    createdAt: "2024-04-12T10:15:00.000Z",
    updatedAt: "2024-04-12T10:15:00.000Z",
  },
  {
    _id: "4",
    requestNumber: "REQ-2024-004",
    requesterId: {
      _id: "user4",
      fullName: "Mohammed Ali",
      email: "ali@example.com",
      phone: "01645678901",
      bloodGroup: "AB+",
    },
    patientName: "Fatima Ali",
    patientAge: 65,
    patientGender: "female",
    patientCondition: "Cancer treatment",
    bloodGroup: "AB+",
    unitsRequired: 4,
    componentType: "red_cells",
    hospital: "Khulna Medical College Hospital",
    division: "Khulna",
    district: "Khulna",
    doctorName: "Dr. Hasan Mahmud",
    doctorContact: "01854321098",
    urgencyLevel: "normal",
    requiredBy: "2024-04-20T12:00:00.000Z",
    requiredByTime: "12:00",
    specialInstructions: "Regular transfusion for chemotherapy patient",
    requesterName: "Mohammed Ali",
    relation: "Son",
    contactPhone: "01645678901",
    contactEmail: "ali@example.com",
    status: "pending",
    createdAt: "2024-04-13T09:45:00.000Z",
    updatedAt: "2024-04-13T09:45:00.000Z",
  },
  {
    _id: "5",
    requestNumber: "REQ-2024-005",
    requesterId: {
      _id: "user5",
      fullName: "Priya Das",
      email: "priya@example.com",
      phone: "01556789012",
      bloodGroup: "O-",
    },
    patientName: "Raj Das",
    patientAge: 52,
    patientGender: "male",
    patientCondition: "Heart surgery",
    bloodGroup: "O-",
    unitsRequired: 6,
    componentType: "whole_blood",
    hospital: "Sylhet MAG Osmani Medical College Hospital",
    division: "Sylhet",
    district: "Sylhet",
    ward: "Cardiac Ward",
    doctorName: "Dr. Sumon Chowdhury",
    doctorContact: "01943210987",
    urgencyLevel: "emergency",
    requiredBy: "2024-04-11T18:00:00.000Z",
    requiredByTime: "18:00",
    specialInstructions: "Critical heart surgery, universal donor needed",
    requesterName: "Priya Das",
    relation: "Wife",
    contactPhone: "01556789012",
    alternatePhone: "01756789012",
    contactEmail: "priya@example.com",
    status: "pending",
    notes: "Patient in ICU, surgery scheduled for tomorrow",
    createdAt: "2024-04-10T16:30:00.000Z",
    updatedAt: "2024-04-10T16:30:00.000Z",
  },
  {
    _id: "6",
    requestNumber: "REQ-2024-006",
    requesterId: {
      _id: "user6",
      fullName: "Anika Rahman",
      email: "anika@example.com",
      phone: "01767890123",
      bloodGroup: "A-",
    },
    patientName: "Nabil Rahman",
    patientAge: 8,
    patientGender: "male",
    patientCondition: "Thalassemia",
    bloodGroup: "A-",
    unitsRequired: 2,
    componentType: "red_cells",
    hospital: "Bangabandhu Sheikh Mujib Medical University",
    division: "Dhaka",
    district: "Dhaka",
    doctorName: "Dr. Farhana Akter",
    doctorContact: "01832109876",
    urgencyLevel: "normal",
    requiredBy: "2024-04-18T09:00:00.000Z",
    requiredByTime: "09:00",
    specialInstructions: "Regular transfusion for thalassemia patient",
    requesterName: "Anika Rahman",
    relation: "Mother",
    contactPhone: "01767890123",
    contactEmail: "anika@example.com",
    status: "pending",
    createdAt: "2024-04-14T11:00:00.000Z",
    updatedAt: "2024-04-14T11:00:00.000Z",
  },
];
